server:
  port: 8080

spring:
  application:
    name: store
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    function:
      definition: receiveOrder;orderCanceled;productSand;productChanged
    stream:
      kafka:
        binder:
          brokers: localfood-kafka:9092
      bindings:
        receiveOrder-in-0:
          destination: ${ORDERED_TOPIC}
          group: order
        orderCanceled-out-0:
          destination: order-canceled
        productSand-out-0:
          destination: product-sand
        productChanged-out-0:
          destination: product-changed
